version: '3.9'

services:

  db:
    image: postgres:10.20-alpine3.15
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "jos.munozl@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "80:80"
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db